
name: eleco 

description: Software developer from London, UK.

avatar: https://github.com/identicons/jasonlong.png

footer-links:
  dribbble:
  email:
  facebook:
  flickr:
  github: eleco
  instagram:
  linkedin:
  pinterest:
  rss:  
  twitter: 
  stackoverflow: 
  youtube: 

disqus: elecogithubio

# Enter your Google Analytics web tracking code (e.g. UA-2110908-2) to activate tracking
google_analytics:

url: http://eleco.github.io

baseurl: ""

rss_post_limit: 15

markdown: redcarpet
highlighter: pygments
permalink: /:title/

version: v1.1.0

sass:
  style: :expanded 

gems:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem

exclude:
    - Gemfile
    - Gemfile.lock
    - LICENSE
    - README.md
